/**
 * LAGGADO Lagger Network — Cloudflare Worker
 *
 * Registry of active Laggers (community relay nodes).
 * Uses Cloudflare KV for persistence — free tier supports ~20 active
 * Laggers with 2-minute heartbeat intervals.
 *
 * KV namespace required: LAGGERS
 *   wrangler kv:namespace create LAGGERS
 *
 * API:
 *   POST   /register        — Lagger announces itself (or refreshes heartbeat)
 *   DELETE /leave           — Lagger gracefully unregisters
 *   GET    /laggers          — List active Laggers (optional ?region=SA)
 *   GET    /count            — Total active Laggers count (for the UI counter)
 *
 * Lagger TTL: 5 minutes (2× heartbeat interval). If no heartbeat in 5min,
 * the Lagger is considered offline and removed from the list.
 */

const LAGGER_TTL_SECONDS = 300; // 5 minutes = 2× heartbeat interval
const MAX_LAGGERS        = 500; // safety cap on list size
const ALLOWED_REGIONS    = new Set(["SA", "US", "EU", "ASIA"]);

// ── Request router ────────────────────────────────────────────────────────────

export default {
  async fetch(request, env) {
    const url    = new URL(request.url);
    const method = request.method.toUpperCase();
    const path   = url.pathname.replace(/\/$/, "") || "/";

    // CORS — allow the LAGGADO desktop app (Electron/WebView or direct HTTP)
    const headers = {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, DELETE, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    };

    if (method === "OPTIONS") {
      return new Response(null, { status: 204, headers });
    }

    try {
      if (method === "POST"   && path === "/register") return handleRegister(request, env, headers);
      if (method === "DELETE" && path === "/leave")    return handleLeave(request, env, headers);
      if (method === "GET"    && path === "/laggers")  return handleList(request, env, headers);
      if (method === "GET"    && path === "/count")    return handleCount(env, headers);
      if (method === "GET"    && path === "/health")   return json({ ok: true, ts: Date.now() }, headers);

      return json({ error: "not found" }, headers, 404);
    } catch (err) {
      return json({ error: err.message }, headers, 500);
    }
  },
};

// ── POST /register ────────────────────────────────────────────────────────────
// Body: { id, region, wgPublicKey, endpoint, city?, country?, version? }
//
// `id`          — stable random UUID generated by the client on first launch,
//                 persisted locally. Identifies this Lagger across restarts.
// `region`      — "SA" | "US" | "EU" | "ASIA"
// `wgPublicKey` — WireGuard public key for this Lagger node
// `endpoint`    — "IP:PORT" reachable by other peers (after UPnP mapping)
// `city`        — optional human label (e.g. "São Paulo")
// `country`     — optional ISO-2 code (e.g. "BR")
// `version`     — optional app version string

async function handleRegister(request, env, headers) {
  let body;
  try {
    body = await request.json();
  } catch {
    return json({ error: "invalid JSON body" }, headers, 400);
  }

  const { id, region, wgPublicKey, endpoint, relayApi, city, country, version } = body;

  if (!id || typeof id !== "string" || id.length < 8 || id.length > 64) {
    return json({ error: "id is required (8-64 chars)" }, headers, 400);
  }
  if (!ALLOWED_REGIONS.has(region)) {
    return json({ error: `region must be one of: ${[...ALLOWED_REGIONS].join(", ")}` }, headers, 400);
  }
  if (!wgPublicKey || wgPublicKey.length < 40 || wgPublicKey.length > 50) {
    return json({ error: "wgPublicKey must be a valid WireGuard public key" }, headers, 400);
  }
  if (!endpoint || !endpoint.includes(":")) {
    return json({ error: "endpoint must be IP:PORT" }, headers, 400);
  }

  // Derive the caller's IP as a fallback for the endpoint host validation
  const callerIP = request.headers.get("CF-Connecting-IP") || "unknown";

  const lagger = {
    id,
    region,
    wgPublicKey,
    endpoint,
    relayApi: relayApi || null, // optional HTTP relay API URL (e.g. "http://IP:7735")
    city:    city    || null,
    country: country || null,
    version: version || null,
    callerIP,
    registeredAt: Date.now(),
    lastSeen:     Date.now(),
  };

  // KV key: "lagger:{id}" — TTL auto-expires the entry if heartbeat stops
  await env.LAGGERS.put(
    `lagger:${id}`,
    JSON.stringify(lagger),
    { expirationTtl: LAGGER_TTL_SECONDS }
  );

  return json({ ok: true, ttl: LAGGER_TTL_SECONDS }, headers);
}

// ── DELETE /leave ─────────────────────────────────────────────────────────────
// Body: { id }

async function handleLeave(request, env, headers) {
  let body;
  try {
    body = await request.json();
  } catch {
    return json({ error: "invalid JSON body" }, headers, 400);
  }

  const { id } = body;
  if (!id) return json({ error: "id required" }, headers, 400);

  await env.LAGGERS.delete(`lagger:${id}`);
  return json({ ok: true }, headers);
}

// ── GET /laggers ──────────────────────────────────────────────────────────────
// Query params: ?region=SA (optional filter)
// Returns list of active Laggers with connection info.

async function handleList(request, env, headers) {
  const url    = new URL(request.url);
  const region = url.searchParams.get("region")?.toUpperCase() || null;

  if (region && !ALLOWED_REGIONS.has(region)) {
    return json({ error: `unknown region: ${region}` }, headers, 400);
  }

  const list = await env.LAGGERS.list({ prefix: "lagger:", limit: MAX_LAGGERS });

  const laggers = [];
  for (const key of list.keys) {
    const raw = await env.LAGGERS.get(key.name);
    if (!raw) continue;

    let lagger;
    try { lagger = JSON.parse(raw); } catch { continue; }

    // Filter by region if requested
    if (region && lagger.region !== region) continue;

    // Don't expose WireGuard key or internal fields in the listing
    // (clients get the full key only during the tunnel setup handshake)
    laggers.push({
      id:       lagger.id,
      region:   lagger.region,
      endpoint: lagger.endpoint,
      relayApi: lagger.relayApi, // null if not a full relay node
      city:     lagger.city,
      country:  lagger.country,
      lastSeen: lagger.lastSeen,
    });
  }

  return json({ laggers, count: laggers.length, ts: Date.now() }, headers);
}

// ── GET /count ────────────────────────────────────────────────────────────────
// Lightweight endpoint for the UI counter badge — avoids reading all values.

async function handleCount(env, headers) {
  const list = await env.LAGGERS.list({ prefix: "lagger:", limit: MAX_LAGGERS });
  return json({ count: list.keys.length, ts: Date.now() }, headers);
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function json(data, headers, status = 200) {
  return new Response(JSON.stringify(data), { status, headers });
}
